function printStatsProgress(path, str, elapsedTime, idxSimType, totalSimType, filled, totalFill, eq, cntEq)

percentage  = (100 * ((idxSimType-1)*totalFill*cntEq + filled*cntEq + eq)) / ...
    (totalSimType * totalFill * cntEq);
remainingTime = elapsedTime*(100-percentage)/percentage;

text = path;
text = [text newline str];
text = [text newline '                          ' , num2str(totalSimType), '×', num2str(totalFill), '×', num2str(cntEq)];
text = [text newline '                          ' , num2str(idxSimType, ['%0',num2str(numel(num2str(totalSimType))),'i']), ...
                                               ':', num2str(filled, ['%0',num2str(numel(num2str(totalFill))),'i']), ...
                                               ':', num2str(eq)];
text = [text newline '                          %', num2str(round(percentage,3))];
text = [text newline '            Elapsed time: ', ...
    num2str((   round(elapsedTime/3600 - 0.5)),      '%02i'), 'h ', ...
    num2str(mod(round(elapsedTime/60   - 0.5) , 60), '%02i'), 'm ', ...
    num2str(mod(round(elapsedTime),60),              '%02i'), 's ', ...
    '(', datestr(now-(elapsedTime/86400),'dd-mmm-yyyy HH:MM'), ')'];
if(0~=remainingTime)
    text = [text newline 'Estimated remaining time: ', ...
        num2str((   round(remainingTime/3600 - 0.5)),      '%02i'), 'h ', ...
        num2str(mod(round(remainingTime/60   - 0.5) , 60), '%02i'), 'm ', ...
        num2str(mod(round(remainingTime),60),              '%02i'), 's ', ...
        '(', datestr(now+(remainingTime/86400),'dd-mmm-yyyy HH:MM'), ')'];
end
clc;
disp(text);

end %end of function
